### ISSUE TITLE
add seeker to video player

### ISSUE THREAD

**Issue by sgsm74** [appinioGmbH/flutter_packages#138]
How can I add seeker to video player?

**Comment by khanmujeeb687** [comment]
Hey @sgsm74 , If I am correct then you want to seek to a position using controller right ( You can achieve it like this `    _customVideoPlayerController.videoPlayerController.seekTo(position)
)`   This method will be available directly in `CustomVideoPlayerController` from the next version ? Otherwise if you need a slider to seek then it is already available in the current example.

**Comment by sgsm74** [comment]
Just like youtube that you can seek video forward 10 seconds, I meant that.

**Comment by khanmujeeb687** [comment]
Hey @sgsm74 , web uses native web player, so for that its not possible right now. But for other platforms this feature will be available from next version.

**Comment by sgsm74** [comment]
Thank you but I was in rush and forked the repo and changed it by myself.
